#store training data in a list here.


title_list = [
    "Wail of Name",
    "Family Histories",
    "Ethnology of the Name",
    "Song of a Speaker",
    "Song of Name",
    "Mourning Song for Name",
    "Feast Song",
    "Shaman's Songs",
    "Love Song",
    "Retort to the Preceding Love Song",
    "Love-Song of Name",
    "Dog Hair",
    "Prayer of the Salmon-Fisher",
    "Prayer to the Lark",
    "Disposal of Property of a Deceased Person",
    "The Spirits of the Fire",
    "Marriage Laws",
    "Property Rights",
    "Inheritance",
    "Domestic Quarrels",
    "Blood Revenge",
    "War Against the Sanetch",
    "Name's War Song Against the Name",
    "Murder After the Death of Name's Child",
    "Roasted Mountain-Goat Meat",
    "Mountain-Goat Skin",
    "Dried Halibut",
    "Backbones of Salmon",
    "Digging Lily-Bulbs",
    "Digging-Stick for Roots",
    "Cedar Withes",
    "Cedar Bark",
    "The Making of Horn Spoons",
    "Sewing with Cedar Withes",
    "Roasted Mountain-Goat Meat",
    "Always Living at Olachen Place",
    "Song-Dance",
    "Abalone Ear Ornament Woman",
    "Good One",
    "Great Liberal One",
    "The Two Slave Girls",
    "Head Winter Dancer",
    "Who Became Chief by Hunting on Sea",
    "The Thunderbird",
    "The Frog Woman",
    "Ten Clan Tribe",
    "Seaward Dwellers",
    "Southeast Wind",
    "Harpooneer",
    "Weight on Floor",
    "Heat Giver",
    "Counsellor of the World",
    "Salmon Boy",
    "Herrings",
    "Ghosts",
    "Seal Hunters",
    "The Origin of the Salmon",
    "Counsellor of the World",
    "Born to be River of Wealth",
    "The Troubled Ones",
    "Post of Heaven",
    "The Halibut",
    "The Origin of the Haida Dance",
    "Great River",
    "The Woodman",
    "The Merman",
    "Weight on Floor",
    "Southeast Wind",
    "Name Song",
    "Song of Name",
    "Name's Song"
]
